# Generated by Django 5.2.8 on 2025-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_shares'),
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='tags.tag'),
        ),
    ]
